import UIKit

struct FlatColors{
    static let softRed = UIColor(rgb: 0xEC644B)
    static let chestnutRose = UIColor(rgb: 0xD24D57)
    static let pomagrante = UIColor(rgb: 0xF22613)
    static let thunderBird = UIColor(rgb: 0xD91E18)
    static let oldBrick = UIColor(rgb: 0x96281B)
    static let flamingo = UIColor(rgb: 0xEF4836)
    static let valencia = UIColor(rgb: 0xD64541)
    static let tallPoppy = UIColor(rgb: 0xC0392B)
    static let monza = UIColor(rgb: 0xCF000F)
    static let cinnabar = UIColor(rgb: 0xE74C3C)
    static let razzmatazz = UIColor(rgb: 0xDB0A5B)
    static let sunsetOrange = UIColor(rgb: 0xF64747)
    static let waxFlower = UIColor(rgb: 0xF1A9A0)
    static let cabaret = UIColor(rgb: 0xD2527F)
    static let newYorkPink = UIColor(rgb: 0xE08283)
    static let radicalRed = UIColor(rgb: 0xF62459)
    static let sunglo = UIColor(rgb: 0xE26A6A)
    static let snuff = UIColor(rgb: 0xDCC6E0)
    static let rebeccaPurple = UIColor(rgb: 0x663399)
    static let honeyFlower = UIColor(rgb: 0x674172)
    static let wistful = UIColor(rgb: 0xAEA8D3)
    static let plum = UIColor(rgb: 0x913D88)
    static let seance = UIColor(rgb: 0x9A12B3)
    static let mediumPurple = UIColor(rgb: 0xBF55EC)
    static let lightWisteria = UIColor(rgb: 0xBE90D4)
    static let studio = UIColor(rgb: 0x8E44AD)
    static let wisteria = UIColor(rgb: 0x9B59B6)
    static let sanMarino = UIColor(rgb: 0x446CB3)
    static let aliceBlue = UIColor(rgb: 0xE4F1FE)
    static let royalBlue = UIColor(rgb: 0x4183D7)
    static let pictonBlue = UIColor(rgb: 0x59ABE3)
    static let spray = UIColor(rgb: 0x81CFE0)
    static let shakespeare = UIColor(rgb: 0x52B3D9)
    static let hummingBird = UIColor(rgb: 0xC5EFF7)
    static let curiousBlue = UIColor(rgb: 0x3498DB)
    static let madison = UIColor(rgb: 0x2C3E50)
    static let dodgerBlue = UIColor(rgb: 0x19B5FE)
    static let ming = UIColor(rgb: 0x336E7B)
    static let ebonyClay = UIColor(rgb: 0x22313F)
    static let malibu = UIColor(rgb: 0x6BB9F0)
    static let summerSky = UIColor(rgb: 0x1E8BC3)
    static let chambray = UIColor(rgb: 0x3A539B)
    static let pickledBluewood = UIColor(rgb: 0x34495E)
    static let hoki = UIColor(rgb: 0x67809F)
    static let jellyBean = UIColor(rgb: 0x2574A9)
    static let jacksonsPurple = UIColor(rgb: 0x1F3A93)
    static let jordyBlue = UIColor(rgb: 0x89C4F4)
    static let steelBlue = UIColor(rgb: 0x4B77BE)
    static let fountainBlue = UIColor(rgb: 0x5C97BF)
    static let mediumTurquise = UIColor(rgb: 0x4ECDC4)
    static let aquaIsland = UIColor(rgb: 0xA2DED0)
    static let gossip = UIColor(rgb: 0x87D37C)
    static let darkSeeGreen = UIColor(rgb: 0x90C695)
    static let eucalyptus = UIColor(rgb: 0x26A65B)
    static let caribbeanSea = UIColor(rgb: 0x03C9A9)
    static let silverTree = UIColor(rgb: 0x68C3A3)
    static let downy = UIColor(rgb: 0x65C6BB)
    static let mountainMeadow = UIColor(rgb: 0x1BBC9B)
    static let lightSeaGreen = UIColor(rgb: 0x1BA39C)
    static let mediumAquamarine = UIColor(rgb: 0x66CC99)
    static let turquoise = UIColor(rgb: 0x36D7B7)
    static let madang = UIColor(rgb: 0xC8F7C5)
    static let riptide = UIColor(rgb: 0x86E2D5)
    static let shamrock = UIColor(rgb: 0x2ECC71)
    static let niagara = UIColor(rgb: 0x16A085)
    static let emerald = UIColor(rgb: 0x3FC380)
    static let greenHaze = UIColor(rgb: 0x019875)
    static let freeSpeechAquamarine = UIColor(rgb: 0x03A678)
    static let oceanGreen = UIColor(rgb: 0x4DAF7C)
    static let niagaraOne = UIColor(rgb: 0x2ABB9B)
    static let jade = UIColor(rgb: 0x00B16A)
    static let salem = UIColor(rgb: 0x1E824C)
    static let observatory = UIColor(rgb: 0x049372)
    static let jungleGreen = UIColor(rgb: 0x26C281)
    static let confetti = UIColor(rgb: 0xE9D460)
    static let capeHoney = UIColor(rgb: 0xFDE3A7)
    static let california = UIColor(rgb: 0xF89406)
    static let fireBush = UIColor(rgb: 0xEB9532)
    static let tahitiGold = UIColor(rgb: 0xE87E04)
    static let casablanca = UIColor(rgb: 0xF4B350)
    static let crusta = UIColor(rgb: 0xF2784B)
    static let seaBuckthorn = UIColor(rgb: 0xEB974E)
    static let lightningYellow = UIColor(rgb: 0xF5AB35)
    static let burntOrange = UIColor(rgb: 0xD35400)
    static let buttercup = UIColor(rgb: 0xF39C12)
    static let ecstasy = UIColor(rgb: 0xF9690E)
    static let sandstorm = UIColor(rgb: 0xF9BF3B)
    static let jaffa = UIColor(rgb: 0xF27935)
    static let zest = UIColor(rgb: 0xE67E22)
    static let whiteSmoke = UIColor(rgb: 0xECECEC)
    static let lynch = UIColor(rgb: 0x6C7A89)
    static let pumice = UIColor(rgb: 0xD2D7D3)
    static let gallery = UIColor(rgb: 0xEEEEEE)
    static let silverSand = UIColor(rgb: 0xBDC3C7)
    static let porcelain = UIColor(rgb: 0xECF0F1)
    static let cascade = UIColor(rgb: 0x95A5A6)
    static let iron = UIColor(rgb: 0xDADFE1)
    static let edward = UIColor(rgb: 0xABB7B7)
    static let cararra = UIColor(rgb: 0xF2F1EF)
    static let silver = UIColor(rgb: 0xBFBFBF)
    
    static let allColors = [FlatColors.softRed, FlatColors.chestnutRose, FlatColors.pomagrante, FlatColors.thunderBird, FlatColors.oldBrick, FlatColors.flamingo, FlatColors.valencia, FlatColors.tallPoppy,FlatColors.monza, FlatColors.cinnabar, FlatColors.razzmatazz, FlatColors.sunsetOrange, FlatColors.waxFlower, FlatColors.cabaret, FlatColors.newYorkPink, FlatColors.radicalRed, FlatColors.sunglo, FlatColors.snuff, FlatColors.rebeccaPurple, FlatColors.honeyFlower, FlatColors.wistful, FlatColors.plum, FlatColors.seance, FlatColors.mediumPurple, FlatColors.lightWisteria, FlatColors.studio, FlatColors.wisteria, FlatColors.sanMarino, FlatColors.aliceBlue, FlatColors.royalBlue, FlatColors.pictonBlue, FlatColors.spray, FlatColors.shakespeare, FlatColors.hummingBird, FlatColors.curiousBlue, FlatColors.madison, FlatColors.dodgerBlue, FlatColors.ming, FlatColors.ebonyClay, FlatColors.malibu, FlatColors.summerSky, FlatColors.chambray, FlatColors.pickledBluewood, FlatColors.hoki, FlatColors.jellyBean, FlatColors.jacksonsPurple, FlatColors.jordyBlue, FlatColors.steelBlue, FlatColors.fountainBlue, FlatColors.mediumTurquise, FlatColors.aquaIsland, FlatColors.gossip, FlatColors.darkSeeGreen, FlatColors.eucalyptus, FlatColors.caribbeanSea, FlatColors.silverTree, FlatColors.downy, FlatColors.mountainMeadow, FlatColors.lightSeaGreen, FlatColors.mediumAquamarine, FlatColors.turquoise, FlatColors.madang, FlatColors.riptide, FlatColors.shamrock, FlatColors.niagara, FlatColors.emerald, FlatColors.greenHaze, FlatColors.freeSpeechAquamarine, FlatColors.oceanGreen, FlatColors.niagaraOne, FlatColors.jade, FlatColors.salem, FlatColors.observatory, FlatColors.jungleGreen, FlatColors.confetti, FlatColors.capeHoney, FlatColors.california, FlatColors.fireBush, FlatColors.tahitiGold, FlatColors.casablanca, FlatColors.crusta, FlatColors.seaBuckthorn, FlatColors.lightningYellow, FlatColors.burntOrange, FlatColors.buttercup, FlatColors.ecstasy, FlatColors.sandstorm, FlatColors.jaffa, FlatColors.zest, FlatColors.whiteSmoke, FlatColors.lynch, FlatColors.pumice, FlatColors.gallery, FlatColors.silverSand, FlatColors.porcelain, FlatColors.cascade, FlatColors.iron, FlatColors.edward, FlatColors.cararra]
}

extension UIColor{
    convenience init(rgb: Int) {
        let r = CGFloat((rgb & 0xFF0000) >> 16)/255
        let g = CGFloat((rgb & 0xFF00) >> 8)/255
        let b = CGFloat(rgb & 0xFF)/255
        self.init(red: r, green: g, blue: b, alpha: 1.0)
    }
}
